### ISSUE TITLE
feat: parsing configuration files

### ISSUE THREAD

**Issue by Sentimentron** [Sentimentron/authentricatron#1]
Obviously, to use Authenticatron, we'll need to configure it. The plan is to create two file formats:
* [ ] A file which contains server runtime configuration - HTTPS, port number, FQDN etc
* [ ] Files which contain information about application configuration.

Application configuration will be referenced in the server configuration, so new applications can be added and removed from Authenticatron.

**Server configuration**
- [x] Port number
- [x] Network interface
- [x] FQDN
- [x] Database details (or where to find them).

**Application configuration**
- [ ] Application name
- [ ] Application prefix
- [ ] Application URL rewrite rules
- [ ] Labels
- [ ] Roles

**Tasks**
- [x] Write an XSD schema for the server configuration.
- [ ] Write an XSD schema for the application configuration.
- [ ] Write a sample configuration file for server. 
- [ ] Write a sample application file for the guestbook example.
- [ ] Write a method (`config.CheckApplicationConfigSyntax`) which checks whether the XML file conforms to the XSD.
- [ ] Write a Method (`config.CheckApplicationConfigSemantics`) which checks e.g. that all referenced files in the XML file are available and readable.
- [ ] Write a method (`config.CheckServerConfigSyntax`)
- [ ] Write a method (`config.CheckServerConfigSemantics`)
- [ ] Security considerations #2 

**Flow info**
Name of branch: *config*
