### ISSUE TITLE
feat: secure runtime configuration secrets

### ISSUE THREAD

**Issue by Sentimentron** [Sentimentron/authentricatron#2]
We'll have to come up with a way of securely storing sensitive runtime configuration (e.g. database passwords), without being publicly readable. The thought is something like this:
* Insist on the application configuration file being only read-write by root
* Insist on things like HTTPs keys only being read-write by root
* Insist that the main server is started only by the root user (e.g. via sudo)
* Start the server again under the active user account (sandboxed?)
* Inject the runtime configuration into the server in a secure way.

**Tasks**
- [ ] Implement a function (`config.CheckPermissions`) which checks for root R/W access (and only that).
- [ ] Implement a check that the main server is started with sudo powers (`config.CheckServerStartedWithSudo`) (not the root user).
- [ ] Implement a fork that starts off a subsidiary server with reduced powers (`config.GenerateRestrictedCommandLine`)
- [ ] Implement a way of injecting configuration etc into the restricted server.

**Flow info**
Branch name: _config-secure_
